# This is a basic workflow to help you get started with Actions

name: CI3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download embeddable python zip and get-pip.py
        run: |
          Invoke-WebRequest https://www.python.org/ftp/python/3.8.9/python-3.8.9-embed-amd64.zip -OutFile .\python.zip
          Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py -OutFile .\get-pip.py
          ls .\
      - name: Extract embeddable python
        run: |
          Expand-Archive -Path .\python.zip -DestinationPath .\python
          ls .\python\
      - name: Execute get-pip.py
        run: |
          .\python\python.exe .\get-pip.py
          ls .\python\
          .\python\python.exe -m pip -V
      - name: Test pip
        run: |
          .\python\python.exe -m pip install requests
          ls .\python\Lib\
          .\python\python.exe -c "import requests; print(requests.__version__)"
          .\python\python.exe -m pip uninstall -y requests

          
          
          
